[build-system]
requires = ["scikit-build-core>=0.3.3", "pybind11"]
build-backend = "scikit_build_core.build"

[project]
name = "mpool"
version = "0.0.1"
requires-python = ">=3.7"

[tool.scikit-build]
cmake.build-type = "Release"